import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

public class Juego extends javax.swing.JFrame {
String[] preguntas = {
"Como se llama la capital de mexico?",
        "Nombre del presidente actual de mexico?",
        "en cual continente esta Mexico",
        "Que idioma se habla en mexico?",

};
String[][] opciones = {
    {"Ciudad de mexico", "Estado de mexico", "Distrito Federal","Sonora"},
    {"Enrique", "Andres Manuel", "Felipe calderon","Carlos"},
    {"Africa","Asia","America","Europa"},
    {"Ingles","Frances","Italiano","Castellano"},    
};
  char[] respuestas = {
     'A',
      'B',
      'C',
      'D',
  }; 
  char adivina;
  char respuesta;
  int index;
  int correctas = 0;
  int resultado;
  int total_preguntas = preguntas.length;
  int segundos = 10;
  
  Timer timer = new Timer(1000, new ActionListener(){
  @Override
  public void actionPerformed(ActionEvent e){
  segundos --;
  labelSegundos.setText(String.valueOf(segundos));
  if(segundos <= 0){
  verRespuesta();
  }
  }
  
  });
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
        siguientePregunta();
    }
    private void verRespuesta(){
    timer.stop();
    botonA.setEnabled(false);
    botonB.setEnabled(false);
    botonC.setEnabled(false);
    botonD.setEnabled(false);
    
    if(respuestas[index] !='A'){
    respuestaA.setForeground(Color.RED);
    }
    if(respuestas[index] !='B'){
    respuestaB.setForeground(Color.RED);
    }
    if(respuestas[index] !='C'){
    respuestaC.setForeground(Color.RED);
    }
    if(respuestas[index] !='D'){
    respuestaD.setForeground(Color.RED);
    }
    Timer pause = new Timer(2000,new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e){
    respuestaA.setForeground(Color.BLACK);
    respuestaB.setForeground(Color.BLACK);
    respuestaC.setForeground(Color.BLACK);
    respuestaD.setForeground(Color.BLACK);
   respuesta =' ';
   segundos = 10;
   labelSegundos.setText(String.valueOf(segundos));
   botonA.setEnabled(true);
   botonB.setEnabled(true);
   botonC.setEnabled(true);
   botonD.setEnabled(true);
   index ++;
   siguientePregunta();
    }
    
    });
    pause.setRepeats(false);
    pause.start();
    }
    
    private void resultadoFinal(){
    botonA.setEnabled(false);    
    respuestaB.setEnabled(false);    
    respuestaC.setEnabled(false);    
    botonD.setEnabled(false);   
    resultado = (int)((correctas/(double)total_preguntas) * 100);
    field.setText("Resultado");
    area.setText("");
    respuestaA.setText("");
    respuestaB.setText("");
    respuestaC.setText("");
    respuestaD.setText("");
    
    buenas.setText("Correctas\n" + "(" + correctas + "/" + total_preguntas+ ")");
    porcentage.setText("Porcentage\n"+ resultado +"%");
    labelSegundos.setVisible(false);
   
    }
    private void siguientePregunta(){
    if(index>= total_preguntas){
    resultadoFinal();
    
    }else{
   field.setText("Pregunta:" +(index+1));
area.setText(preguntas[index]);
respuestaA.setText(opciones[index][0]);
respuestaB.setText(opciones[index][1]);
respuestaC.setText(opciones[index][2]);
respuestaD.setText(opciones[index][3]);
timer.start();
   
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        field = new javax.swing.JTextField();
        area = new javax.swing.JTextField();
        botonA = new javax.swing.JButton();
        botonB = new javax.swing.JButton();
        botonC = new javax.swing.JButton();
        botonD = new javax.swing.JButton();
        respuestaA = new javax.swing.JTextField();
        respuestaB = new javax.swing.JTextField();
        respuestaC = new javax.swing.JTextField();
        respuestaD = new javax.swing.JTextField();
        buenas = new javax.swing.JTextField();
        porcentage = new javax.swing.JTextField();
        labelSegundos = new javax.swing.JTextField();
        field1 = new javax.swing.JTextField();
        area1 = new javax.swing.JTextField();
        botonA1 = new javax.swing.JButton();
        botonB1 = new javax.swing.JButton();
        botonC1 = new javax.swing.JButton();
        botonD1 = new javax.swing.JButton();
        respuestaA2 = new javax.swing.JTextField();
        respuestaB1 = new javax.swing.JTextField();
        respuestaC1 = new javax.swing.JTextField();
        respuestaD1 = new javax.swing.JTextField();
        buenas1 = new javax.swing.JTextField();
        porcentage1 = new javax.swing.JTextField();
        labelSegundos1 = new javax.swing.JTextField();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        field.setText("Pregunta:1");

        area.setText("jTextField2");

        botonA.setText("A");
        botonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAActionPerformed(evt);
            }
        });

        botonB.setText("B");
        botonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBActionPerformed(evt);
            }
        });

        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });

        botonD.setText("D");
        botonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDActionPerformed(evt);
            }
        });

        respuestaA.setText("jTextField2");

        respuestaB.setText("jTextField2");

        respuestaC.setText("jTextField2");

        respuestaD.setText("jTextField2");

        buenas.setText("Buenas");

        porcentage.setText("Porcentage");

        labelSegundos.setText("jTextField2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field)
                    .addComponent(area)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonA, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(botonB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(respuestaA, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addComponent(respuestaB)
                            .addComponent(respuestaC)
                            .addComponent(respuestaD))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buenas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuestaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuestaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuestaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(buenas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porcentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(respuestaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        field1.setText("Pregunta:1");

        area1.setText("jTextField2");

        botonA1.setText("A");
        botonA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA1ActionPerformed(evt);
            }
        });

        botonB1.setText("B");
        botonB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonB1ActionPerformed(evt);
            }
        });

        botonC1.setText("C");
        botonC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonC1ActionPerformed(evt);
            }
        });

        botonD1.setText("D");
        botonD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonD1ActionPerformed(evt);
            }
        });

        respuestaA2.setText("jTextField2");

        respuestaB1.setText("jTextField2");

        respuestaC1.setText("jTextField2");

        respuestaD1.setText("jTextField2");

        buenas1.setText("Buenas");

        porcentage1.setText("Porcentage");

        labelSegundos1.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(field1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(area1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonD1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(botonC1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonB1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonA1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(respuestaC1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(respuestaA2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addComponent(respuestaB1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(respuestaD1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buenas1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentage1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSegundos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonA1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuestaA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonB1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuestaB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonC1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuestaC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonD1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(respuestaD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelSegundos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buenas1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentage1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAActionPerformed
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);

        if(evt.getSource() == botonA){
            respuesta = 'A';
            if(respuesta == respuestas[index]){
                correctas++;
            }
        }
        verRespuesta();        // TODO add your handling code here:
    }//GEN-LAST:event_botonAActionPerformed

    private void botonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBActionPerformed
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);

        if(evt.getSource() == botonB){
            respuesta = 'B';
            if(respuesta == respuestas[index]){
                correctas++;
            }
        }
        verRespuesta();   // TODO add your handling code here:
    }//GEN-LAST:event_botonBActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);

        if(evt.getSource() == botonC){
            respuesta = 'C';
            if(respuesta == respuestas[index]){
                correctas++;
            }
        }
        verRespuesta();         // TODO add your handling code here:
    }//GEN-LAST:event_botonCActionPerformed

    private void botonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDActionPerformed
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);

        if(evt.getSource() == botonD){
            respuesta = 'D';
            if(respuesta == respuestas[index]){
                correctas++;
            }
        }
        verRespuesta();   // TODO add your handling code here:
    }//GEN-LAST:event_botonDActionPerformed

    private void botonA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA1ActionPerformed
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);

        if(evt.getSource() == botonA){
            respuesta = 'A';
            if(respuesta == respuestas[index]){
                correctas++;
            }
        }
        verRespuesta();        // TODO add your handling code here:
    }//GEN-LAST:event_botonA1ActionPerformed

    private void botonB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonB1ActionPerformed
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);

        if(evt.getSource() == botonB){
            respuesta = 'B';
            if(respuesta == respuestas[index]){
                correctas++;
            }
        }
        verRespuesta();   // TODO add your handling code here:
    }//GEN-LAST:event_botonB1ActionPerformed

    private void botonC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonC1ActionPerformed
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);

        if(evt.getSource() == botonC){
            respuesta = 'C';
            if(respuesta == respuestas[index]){
                correctas++;
            }
        }
        verRespuesta();         // TODO add your handling code here:
    }//GEN-LAST:event_botonC1ActionPerformed

    private void botonD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonD1ActionPerformed
        botonA.setEnabled(false);
        botonB.setEnabled(false);
        botonC.setEnabled(false);
        botonD.setEnabled(false);

        if(evt.getSource() == botonD){
            respuesta = 'D';
            if(respuesta == respuestas[index]){
                correctas++;
            }
        }
        verRespuesta();   // TODO add your handling code here:
    }//GEN-LAST:event_botonD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JTextField area1;
    private javax.swing.JButton botonA;
    private javax.swing.JButton botonA1;
    private javax.swing.JButton botonB;
    private javax.swing.JButton botonB1;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonC1;
    private javax.swing.JButton botonD;
    private javax.swing.JButton botonD1;
    private javax.swing.JTextField buenas;
    private javax.swing.JTextField buenas1;
    private javax.swing.JTextField field;
    private javax.swing.JTextField field1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JTextField labelSegundos;
    private javax.swing.JTextField labelSegundos1;
    private javax.swing.JTextField porcentage;
    private javax.swing.JTextField porcentage1;
    private javax.swing.JTextField respuestaA;
    private javax.swing.JTextField respuestaA2;
    private javax.swing.JTextField respuestaB;
    private javax.swing.JTextField respuestaB1;
    private javax.swing.JTextField respuestaC;
    private javax.swing.JTextField respuestaC1;
    private javax.swing.JTextField respuestaD;
    private javax.swing.JTextField respuestaD1;
    // End of variables declaration//GEN-END:variables
}
