/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

/**
 *
 * @author Dell
 */
public class Modos_de_juego extends javax.swing.JFrame {

    /**
     * Creates new form Modos_de_juego
     */
    public Modos_de_juego() {
        initComponents();        
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NuevoJuego = new javax.swing.JButton();
        Menú = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mododejuegi.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -40, 310, 290));

        jLabel2.setFont(new java.awt.Font("Ultraquick", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELECCIONA TU SIGUENTE DESTINO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 460, 80));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 207, 400, 50));

        NuevoJuego.setBackground(new java.awt.Color(255, 222, 8));
        NuevoJuego.setFont(new java.awt.Font("DPComic", 0, 34)); // NOI18N
        NuevoJuego.setText("NUEVO JUEGO");
        NuevoJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        NuevoJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevoJuegoMouseClicked(evt);
            }
        });
        NuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoJuegoActionPerformed(evt);
            }
        });
        jPanel1.add(NuevoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 210, 140));

        Menú.setBackground(new java.awt.Color(0, 0, 0));
        Menú.setFont(new java.awt.Font("DPComic", 0, 34)); // NOI18N
        Menú.setForeground(new java.awt.Color(255, 222, 8));
        Menú.setText("IR AL MENU");
        Menú.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 222, 8), 7));
        Menú.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenúMouseClicked(evt);
            }
        });
        Menú.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenúActionPerformed(evt);
            }
        });
        jPanel1.add(Menú, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 293, 200, 140));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/font2.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenúActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenúActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenúActionPerformed

    private void NuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoJuegoActionPerformed

    private void MenúMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenúMouseClicked
login newframe = new login  ();
        newframe.setVisible(true);
        
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_MenúMouseClicked

    private void NuevoJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoJuegoMouseClicked
LUCKY_WORDS_2 newframe = new LUCKY_WORDS_2  ();
        newframe.setVisible(true);
        
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_NuevoJuegoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modos_de_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modos_de_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modos_de_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modos_de_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modos_de_juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menú;
    private javax.swing.JButton NuevoJuego;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
